"""Skill-trust gate: derived Python bytecode is not skill source drift.

The boot supply-chain gate runs the immutable verifier at
``~/.hermes/security/skill-trust/verify.py`` (invoked from
``norcal/boot/hermes-shared-boot-context``). It pins every approved skill
tree by a recursive content hash and fails closed on any mismatch, so a
non-zero verdict marks the whole boot ``DEGRADED`` and blocks ordinary task
execution.

**The regression this file locks down.** Normal skill loading makes CPython
write ``__pycache__/<mod>.cpython-XX.pyc`` inside the skill tree it just
imported. Those files are *derived* — regenerated from source on demand, not
part of the reviewed payload — but the frozen tree hash originally counted
them, so merely running an approved Python skill mutated its own hash and the
gate reported source drift on the next boot. That drove BOOT DEGRADED
repeatedly, and because the artifacts reappear as soon as the skill runs again,
re-attesting the registry could not settle it. The live verifier now skips
``__pycache__`` members and ``.pyc``/``.pyo`` files, and nothing else.

Both halves of that behaviour are load-bearing and this file asserts both:

1. Derived bytecode must not change the verdict (the fix).
2. Every non-bytecode change — edited, added, removed, or retargeted content —
   must still change the hash and still produce a ``drift:`` failure, because
   the exclusion must not become a hole a payload can hide in (fail closed).

These tests bind to the **live** verifier by absolute path rather than to a
copy in this repo. That is deliberate: the live file is what the boot gate
executes, it is root-owned and ``chattr +i`` immutable, and a repo copy could
drift from it silently. If the live verifier is ever rewritten and loses the
exclusion — or widens it — this suite fails.
"""

import importlib.util
import json
import os
import py_compile
import subprocess
import sys
from pathlib import Path

import pytest

#: The live, immutable verifier the boot gate actually runs. ``HERMES_HOME`` is
#: sandboxed to a tempdir by ``tests/conftest.py``, so it cannot be used to
#: resolve this; ``HOME`` is deliberately left alone there, so ``Path.home()``
#: still points at the operator's real root. The env var is an explicit
#: override for exercising this suite against a staged verifier.
VERIFIER = Path(
    os.environ.get("HERMES_SKILL_TRUST_VERIFIER")
    or (Path.home() / ".hermes" / "security" / "skill-trust" / "verify.py")
)

pytestmark = pytest.mark.skipif(
    not VERIFIER.is_file(),
    reason=f"live skill-trust verifier not present at {VERIFIER}",
)

SKILL_NAME = "regression-demo-skill"


@pytest.fixture(scope="module")
def verifier():
    """Import the live verifier as a module.

    Import is side-effect free: the file only binds constants and functions at
    module level and calls ``main()`` under ``__name__ == "__main__"``.
    """
    spec = importlib.util.spec_from_file_location(
        "hermes_live_skill_trust_verify", VERIFIER
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _make_skill_tree(root: Path) -> Path:
    """A minimal approved-skill-shaped tree: docs, code, and nested data."""
    root.mkdir(parents=True, exist_ok=True)
    (root / "SKILL.md").write_text("# demo skill\n", encoding="utf-8")
    (root / "helper.py").write_text("VALUE = 1\n", encoding="utf-8")
    resources = root / "resources"
    resources.mkdir()
    (resources / "data.json").write_text('{"a": 1}\n', encoding="utf-8")
    return root


class TestDerivedBytecodeIsIgnored:
    """Runtime-generated bytecode must leave the tree hash untouched."""

    def test_real_py_compile_artifacts_do_not_change_tree_hash(
        self, verifier, tmp_path
    ):
        """The exact artifact CPython writes when an approved skill is loaded.

        Uses ``py_compile`` rather than hand-written files so the test tracks
        whatever layout and filename the running interpreter actually emits.
        """
        tree = _make_skill_tree(tmp_path / "skill")
        before = verifier.tree_hash(tree)

        py_compile.compile(str(tree / "helper.py"), doraise=True)

        # Guard against a vacuous assertion: prove bytecode really landed
        # inside the tree before claiming the hash ignores it.
        emitted = list((tree / "__pycache__").glob("helper.*.pyc"))
        assert emitted, "py_compile wrote no bytecode into the skill tree"

        assert verifier.tree_hash(tree) == before

    def test_pyc_pyo_and_nested_pycache_are_ignored(self, verifier, tmp_path):
        tree = _make_skill_tree(tmp_path / "skill")
        before = verifier.tree_hash(tree)

        top = tree / "__pycache__"
        top.mkdir()
        (top / "helper.cpython-311.pyc").write_bytes(b"\x00\x0f\x0d\x0a stale")
        (top / "helper.cpython-311.opt-1.pyc").write_bytes(b"\x00 opt")
        (top / "legacy.pyo").write_bytes(b"\x00 pyo")
        nested = tree / "resources" / "__pycache__"
        nested.mkdir()
        (nested / "loader.cpython-313.pyc").write_bytes(b"\x00 nested")

        assert verifier.tree_hash(tree) == before

    def test_sourceless_pyc_beside_source_is_ignored(self, verifier, tmp_path):
        """Characterises the exclusion's full current width.

        The live rule skips any ``.pyc``/``.pyo`` *anywhere* in the tree, not
        only those under ``__pycache__``. A bare ``.pyc`` sitting where a
        module would live is therefore uncovered by the tree hash. Normal skill
        loading never produces that layout — CPython 3 writes to
        ``__pycache__`` — so this documents a residual gap, not a requirement.
        If the live verifier is deliberately tightened to ``__pycache__``-only,
        this test is the one to delete; the two classes below must keep
        passing unchanged.
        """
        tree = _make_skill_tree(tmp_path / "skill")
        before = verifier.tree_hash(tree)

        (tree / "sourceless.pyc").write_bytes(b"\x00 sourceless module")

        assert verifier.tree_hash(tree) == before


class TestSourceDriftStillFailsClosed:
    """Every tracked non-bytecode change must still move the hash."""

    def test_edited_python_source_changes_tree_hash(self, verifier, tmp_path):
        tree = _make_skill_tree(tmp_path / "skill")
        before = verifier.tree_hash(tree)

        (tree / "helper.py").write_text("VALUE = 666\n", encoding="utf-8")

        assert verifier.tree_hash(tree) != before

    def test_edited_nested_data_file_changes_tree_hash(self, verifier, tmp_path):
        tree = _make_skill_tree(tmp_path / "skill")
        before = verifier.tree_hash(tree)

        (tree / "resources" / "data.json").write_text('{"a": 2}\n', encoding="utf-8")

        assert verifier.tree_hash(tree) != before

    def test_edited_instructions_changes_tree_hash(self, verifier, tmp_path):
        """Prompt text is executable in effect — an edit must be caught."""
        tree = _make_skill_tree(tmp_path / "skill")
        before = verifier.tree_hash(tree)

        (tree / "SKILL.md").write_text("# demo skill\nexfiltrate secrets\n", encoding="utf-8")

        assert verifier.tree_hash(tree) != before

    def test_added_file_changes_tree_hash(self, verifier, tmp_path):
        tree = _make_skill_tree(tmp_path / "skill")
        before = verifier.tree_hash(tree)

        (tree / "payload.py").write_text("import os\n", encoding="utf-8")

        assert verifier.tree_hash(tree) != before

    def test_removed_file_changes_tree_hash(self, verifier, tmp_path):
        tree = _make_skill_tree(tmp_path / "skill")
        before = verifier.tree_hash(tree)

        (tree / "helper.py").unlink()

        assert verifier.tree_hash(tree) != before

    def test_renamed_file_changes_tree_hash(self, verifier, tmp_path):
        """Content-only hashing would miss a rename; paths are hashed too."""
        tree = _make_skill_tree(tmp_path / "skill")
        before = verifier.tree_hash(tree)

        (tree / "helper.py").rename(tree / "helper_renamed.py")

        assert verifier.tree_hash(tree) != before

    @pytest.mark.require_symlinks
    def test_retargeted_symlink_changes_tree_hash(self, verifier, tmp_path):
        tree = _make_skill_tree(tmp_path / "skill")
        (tree / "resources" / "alt.json").write_text('{"a": 9}\n', encoding="utf-8")
        link = tree / "active.json"
        link.symlink_to(tree / "resources" / "data.json")
        before = verifier.tree_hash(tree)

        link.unlink()
        link.symlink_to(tree / "resources" / "alt.json")

        assert verifier.tree_hash(tree) != before


class TestExclusionIsNarrow:
    """The skip must match bytecode only — not anything merely named like it.

    These are the shapes a sloppier reimplementation would wrongly exclude
    (``"pycache" in str(p)``, ``".pyc" in p.name``), each of which would let a
    real Python payload ride along unhashed.
    """

    def test_directory_named_pycache_without_dunders_is_covered(
        self, verifier, tmp_path
    ):
        tree = _make_skill_tree(tmp_path / "skill")
        before = verifier.tree_hash(tree)

        plain = tree / "pycache"
        plain.mkdir()
        (plain / "payload.py").write_text("import socket\n", encoding="utf-8")

        assert verifier.tree_hash(tree) != before

    def test_pycache_substring_in_directory_name_is_covered(self, verifier, tmp_path):
        tree = _make_skill_tree(tmp_path / "skill")
        before = verifier.tree_hash(tree)

        sneaky = tree / "my__pycache__helpers"
        sneaky.mkdir()
        (sneaky / "payload.py").write_text("import socket\n", encoding="utf-8")

        assert verifier.tree_hash(tree) != before

    def test_filename_merely_containing_pyc_is_covered(self, verifier, tmp_path):
        tree = _make_skill_tree(tmp_path / "skill")
        before = verifier.tree_hash(tree)

        (tree / "notes.pyc.txt").write_text("not bytecode\n", encoding="utf-8")

        assert verifier.tree_hash(tree) != before

    def test_python_module_named_like_bytecode_is_covered(self, verifier, tmp_path):
        tree = _make_skill_tree(tmp_path / "skill")
        before = verifier.tree_hash(tree)

        (tree / "mypyc.py").write_text("import socket\n", encoding="utf-8")

        assert verifier.tree_hash(tree) != before


class TestRegistryVerdict:
    """End-to-end through ``main()``: what the boot gate reads off stdout.

    ``main()`` resolves its registry from the module-level ``REG`` constant, so
    pointing that at a temp registry exercises the real drift loop without
    touching the live immutable registry. Assertions target the ``drift:``
    line for this fixture's own skill rather than the overall return code:
    with a stand-in registry, every genuinely installed skill and plugin is
    legitimately reported as unregistered, which is unrelated noise here.
    """

    @staticmethod
    def _write_registry(reg_path: Path, tree: Path, tree_hash: str) -> None:
        reg_path.write_text(
            json.dumps(
                {
                    "version": 1,
                    "policy": "frozen-after-review-no-upstream-update",
                    "items": [
                        {
                            "name": SKILL_NAME,
                            "path": str(tree),
                            "sha256_tree": tree_hash,
                            "status": "approved",
                        }
                    ],
                }
            ),
            encoding="utf-8",
        )

    @staticmethod
    def _drift_lines(output: str) -> list[str]:
        return [
            line
            for line in output.splitlines()
            if line.startswith("- drift:") and SKILL_NAME in line
        ]

    def test_generated_bytecode_produces_no_drift_verdict(
        self, verifier, tmp_path, monkeypatch, capsys
    ):
        tree = _make_skill_tree(tmp_path / "skill")
        reg = tmp_path / "registry.json"
        self._write_registry(reg, tree, verifier.tree_hash(tree))
        monkeypatch.setattr(verifier, "REG", reg)

        py_compile.compile(str(tree / "helper.py"), doraise=True)
        assert list((tree / "__pycache__").glob("helper.*.pyc"))

        verifier.main()

        assert self._drift_lines(capsys.readouterr().out) == []

    def test_source_change_produces_drift_verdict_and_nonzero_rc(
        self, verifier, tmp_path, monkeypatch, capsys
    ):
        tree = _make_skill_tree(tmp_path / "skill")
        reg = tmp_path / "registry.json"
        self._write_registry(reg, tree, verifier.tree_hash(tree))
        monkeypatch.setattr(verifier, "REG", reg)

        (tree / "helper.py").write_text("VALUE = 666\n", encoding="utf-8")

        rc = verifier.main()
        out = capsys.readouterr().out

        assert rc != 0
        assert "SKILL TRUST: FAIL" in out
        assert self._drift_lines(out), out

    def test_missing_approved_tree_produces_nonzero_rc(
        self, verifier, tmp_path, monkeypatch, capsys
    ):
        """Deleting a whole approved tree must fail closed, not pass vacuously."""
        tree = _make_skill_tree(tmp_path / "skill")
        reg = tmp_path / "registry.json"
        self._write_registry(reg, tree, verifier.tree_hash(tree))
        monkeypatch.setattr(verifier, "REG", reg)

        for child in sorted(tree.rglob("*"), reverse=True):
            child.unlink() if child.is_file() else child.rmdir()
        tree.rmdir()

        rc = verifier.main()
        out = capsys.readouterr().out

        assert rc != 0
        assert f"missing approved skill: {SKILL_NAME}" in out


class TestLiveGateState:
    """The live gate, against live state, exactly as boot invokes it."""

    def test_live_gate_passes_with_derived_bytecode_present(self, verifier):
        """Derived bytecode exists in approved trees right now and is tolerated.

        This is the end-to-end form of the regression: at the time of writing,
        9 of 184 approved trees carried ``__pycache__`` artifacts from ordinary
        skill use. Before the fix that state was exactly what reported drift
        and marked the boot DEGRADED; now the gate reads PASS with those
        artifacts in place. The bytecode census is reported in the failure
        message so a red run says whether the invariant was even exercised.
        """
        # argv is passed as a list on purpose: conftest's live-system guard
        # full-token-scans string commands and wrapper executables, and
        # "skill" is one of its process-killer tokens.
        proc = subprocess.run(
            [sys.executable, str(VERIFIER)],
            capture_output=True,
            text=True,
            timeout=180,
            check=False,
        )

        # Read the registry the verifier itself resolves, not a path guessed
        # from the verifier's directory.
        registry = json.loads(Path(verifier.REG).read_text(encoding="utf-8"))
        trees_with_bytecode = sum(
            1
            for item in registry.get("items", [])
            if Path(item["path"]).is_dir()
            and any(
                "__pycache__" in p.parts or p.suffix in {".pyc", ".pyo"}
                for p in Path(item["path"]).rglob("*")
            )
        )

        assert proc.returncode == 0, (
            f"live skill-trust gate is not green "
            f"(rc={proc.returncode}, approved trees carrying derived "
            f"bytecode={trees_with_bytecode}):\n{proc.stdout}\n{proc.stderr}"
        )
        assert "SKILL TRUST: PASS" in proc.stdout
